project:
  type: website

website:
  title: "Aid-Worker-Security-Analysis"
  navbar:
    search: true

  sidebar:
    style: "docked"
    contents:
      - href: introduction.qmd
        text: Introduction
      - href: data_processing.ipynb
        text: Data Processing
      - href: dv.ipynb
        text: Data Visualization
      - href: report.ipynb
        text: Story Telling


  
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    sidebar: left
    bibliography:   ./assets/reference.bib
    csl:  ./assets/nature.csl

